server:
  servlet:
    context-path: /api
  port: 8080

#server.servlet.context-path=/api
spring:
  application:
    name: demoProject2
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
#    <!--         jdbc:postgresql://jesus-demo-db.cpekdysfx5nc.us-east-1.rds.amazonaws.com:5432/postgres-->
    url: jdbc:postgresql://project2team3.cbvxzziohfzl.us-east-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"